container:
  image: ubuntu:latest
  cpu: 16
  ram: 4
  greedy: true

build_task:
  script: 
  - ./build.sh whyred
  - curl --upload-file out/arch/arm64/boot/Image.gz-dtb https://transfer.sh
  - make mrproper && rm .config
  - ./build.sh tulip
  - curl --upload-file out/arch/arm64/boot/Image.gz-dtb https://transfer.sh

