# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1


jobs:
  build-kernel:
    docker:
      - image: ubuntu:latest
    resource_class: large
    steps:
      - run:
          name: "Download Dependencies"
          command: "apt-get update && apt-get install -y bison build-essential bc bison curl libssl-dev git zip python2 python3 flex cpio libncurses5-dev wget default-jre"
      - run:
          name: "Clone kernel"
          command: git clone https://github.com/Whyred-Dynamic-Development/san_kernel_sdm660_4 ./ --depth=1
      - run:
          name: "Build Whyred Kernel"
          command: "./build.sh whyred"
      - run:
          name: "Upload Whyred Kernel"
          command: "curl --upload-file out/arch/arm64/boot/Image.gz-dtb https://transfer.sh"          
      - run:
          name: "Clean"
          command: "make mrproper && rm -rf .config && rm -rf out/arch/arm64/boot"
      - run:
          name: "Build Tulip Kernel"
          command: "./build.sh tulip"    
      - run:
          name: "Upload Tulip Kernel"
          command: "curl --upload-file out/arch/arm64/boot/Image.gz-dtb https://transfer.sh"
workflows:
  my_workflow:
    jobs:
      - build-kernel


